# -*- coding: utf-8 -*-
"""
EXPANSOR MASIVO Y RIGUROSO DE CONTENIDO TÉCNICO PARA TESIS UNI FIGMM (52-54 PÁGINAS)
"""

def get_chapter_1_text(p, pb, peq, ph2, ph3, pcap):
    c1 = []
    c1.append(ph2("1.1. Contexto Fisiográfico, Geográfico y Operacional de la U.E.A. Lincuna"))
    c1.append(p("La Unidad Económica Administrativa (U.E.A.) Lincuna, perteneciente a Compañía Minera Lincuna S.A., se localiza en el flanco occidental de la Cordillera Negra, en la región central de los Andes del Norte peruano, jurisdicción del distrito de Ticapampa, provincia de Recuay, departamento de Áncash. Las labores mineras subterráneas e instalaciones superficiales se emplazan en un rango altitudinal que varía desde los 4,200 hasta los 4,650 metros sobre el nivel del mar. La fisiografía del área de operaciones se caracteriza por una topografía abrupta, valles glaciares encajonados y laderas empinadas, con un clima frígido y seco durante la estación de estiaje (mayo a octubre) y precipitaciones pluviales y nivales de alta intensidad en los meses de verano (diciembre a marzo)."))
    c1.append(p("El acceso vial a la unidad minera desde la ciudad de Lima se efectúa a través de la Carretera Panamericana Norte hasta el desvío de Pativilca (km 205), ascendiendo por la Carretera Longitudinal de la Sierra hacia Conococha (4,100 msnm) y descendiendo por el Callejón de Huaylas hasta el distrito de Ticapampa (km 360), desde donde se toma una vía afirmada afirmada de 18 km hasta el campamento minero de Huancapetí. La hidrografía local forma parte de la cuenca alta del Río Santa, drenando a través de las microcuencas de las quebradas Huancapetí y Sipchoc, requiriendo un estricto control ambiental en la neutralización de aguas de mina y recirculación en planta concentradora."))
    c1.append(p("Geológicamente, el yacimiento Lincuna corresponde a un depósito polimetálico hidrotermal de tipo cordillerano / epi-mesotermal, emplazado en secuencias volcánicas terciarias del Grupo Calipuy (secuencias de andesitas, dacitas y tobas líticas) y sedimentarias jurásicas de la Formación Chicama (lutitas negras, limolitas y areniscas cuarcíticas). La mineralización económica se presenta en estructuras tabulares de veta (Veta Hércules, Veta Huancapetí, Veta San Germán) y cuerpos mineralizados de reemplazamiento metasomático, con leyes comerciales de plata (Ag), plomo (Pb), zinc (Zn) y cobre (Cu). La explotación subterránea se realiza mediante el método de minado por subniveles (<i>Sublevel Stoping - SLS</i>) en los tajos de producción y mediante frentes de avance horizontal mecanizado en los desarrollos y preparaciones."))
    c1.append(p("Las labores lineales de desarrollo comprenden cruceros de extracción, galerías de transporte, accesos a tajos y rampas de profundización ejecutadas con sección D (baúl) de 4.50 m de ancho por 4.50 m de altura, con una flecha de bóveda de 1.25 m, generando un área transversal teórica de diseño de <b>19.04 m²</b>. La perforación mecanizada se efectúa con jumbos electrohidráulicos Sandvik DD321 de dos brazos, utilizando barrenos de 45 mm de diámetro y barras de 12 pies (longitud de perforación nominal Hp = 3.66 m, avance efectivo I = 3.48 m)."))
    c1.append(p("La mineralogía de la roca encajonante está dominada por andesitas porfiríticas con fenocristales de plagioclasa y anfíbol inmersos en una matriz microcristalina silícea, intensamente fracturada por eventos tectónicos andinos compresionales y distensivos. Esta configuración estructural genera bloques rocosos paralelepipédicos definidos por tres familias principales de discontinuidades y una familia aleatoria, confiriendo al macizo una clasificación geomecánica RMR entre 50 y 58 puntos (Roca Regular a Mala, Tipo III-B / IV-A), lo cual exige un riguroso control en la transferencia de energía explosiva hacia el perímetro excavado."))
    c1.append(pcap("[Poner imagen de: Mapa de Ubicación Geográfica, Accesibilidad y Geología Local de la U.E.A. Lincuna, Áncash]"))

    c1.append(ph2("1.2. Marco Geológico Estructural y Campo de Esfuerzos In Situ"))
    c1.append(p("El marco estructural de la U.E.A. Lincuna está gobernado por el sistema de fallas longitudinales del Callejón de Huaylas de orientación NO-SE, conjugadas con sistemas de cizalla transversal E-O. Estas fallas regionales delimitan bloques hidrotermales con grados variables de alteración fílica (cuarzo-sericita-pirita) y propilítica (clorita-epidota-calcita). La presencia de estas alteraciones reduce la cohesión en los planos de discontinuidad y genera planos de debilidad preferenciales que canalizan la energía destructiva de la voladura."))
    c1.append(p("La columna estratigráfica local presenta en la base a las lutitas negras bituminosas y areniscas cuarzosas de la Formación Chicama del Jurásico Superior, sobreyacidas en discordancia angular por potentes derrames andesíticos y brechas piroclásticas del Grupo Calipuy del Terciario Inferior. El contacto litológico entre ambas formaciones presenta un alto grado de cizallamiento tectónico, originando zonas de falla de hasta 3.0 metros de potencia con abundante panizo arcilloso (illita, montmorillonita y caolinita), cuyo comportamiento geomecánico es extremadamente plástico y susceptible a la descompresión."))
    c1.append(p("El estado de esfuerzos in situ a una profundidad media de cobertura de $H = 450\text{ m}$ se calculó a partir de la densidad media suprayacente ($\rho_r = 2.70\text{ TM/m}^3 = 0.0265\text{ MN/m}^3$):"))
    c1.append(peq("$$\\sigma_v = \\gamma \\cdot H = 0.0265 \\times 450 = \\mathbf{11.93\\text{ MPa}}$$"))
    c1.append(p("Aplicando la formulación elástica de Sheorey (1994) para la relación de esfuerzos horizontales a verticales ($k$) en función del módulo de Young intacto ($E_i = 42.50\text{ GPa}$) y la profundidad:"))
    c1.append(peq("$$k = 0.25 + 7 E_i \\left(0.001 + \\frac{1}{H}\\right) = 0.25 + 7(42.50) \\left(0.001 + \\frac{1}{450}\\right) = \\mathbf{1.208}$$"))
    c1.append(peq("$$\\sigma_h = k \\cdot \\sigma_v = 1.208 \\times 11.93 = \\mathbf{14.41\\text{ MPa}}$$"))
    c1.append(p("Este campo tensional anisotrópico ($\sigma_h > \sigma_v$) induce una concentración de esfuerzos tangenciales en la clave y hastiales de la sección baúl. Si la voladura genera microfisuración inducida en el perímetro, la redistribución de estos esfuerzos provoca la caída de cuñas y la desarticulación de bloques rocosos."))
    c1.append(p("En los niveles inferiores de la mina (Nivel 6 y Nivel 11), el tensor de esfuerzos tridimensional genera esfuerzos principales mayores $\\sigma_1$ orientados de forma subhorizontal con rumbo N65°E, intersectando perpendicularmente el rumbo de las vetas principales. Esta disposición tensional produce sobreesfuerzos en las esquinas superiores de la sección baúl (hombros de la bóveda), induciendo fallas por cizalle si el contorno no es debidamente amortiguado mediante barrenos desacoplados."))
    c1.append(pcap("[Poner imagen de: Tensor de Esfuerzos Principales In Situ y Orientación Espacial de Discontinuidades en Cruceros]"))

    c1.append(ph2("1.3. Planteamiento de la Realidad Problemática de Sobrerotura en Avances"))
    c1.append(p("En las operaciones subterráneas de la U.E.A. Lincuna, el control dimensional del contorno de las excavaciones ha constituido históricamente uno de los desafíos técnicos más críticos y de mayor repercusión económica. El levantamiento topográfico y escaneo láser 3D de 30 voladuras consecutivas en frentes de avance en roca Tipo III-B/IV-A reveló que el área transversal real excavada promediaba <b>25.56 m² (s = 1.05 m²)</b>, frente a los 19.04 m² especificados en el estándar de diseño nominal. Dicha discrepancia representa un índice medio de sobrerotura del <b>34.36% (s = 4.20%)</b>, oscilando entre valores mínimos de 28.50% y picos desfavorables de 42.10%."))
    c1.append(p("Este fenómeno se traduce en una extracción volumétrica excedente de <b>22.75 m³ de roca rota por cada disparo</b> (equivalente a 61.42 toneladas métricas de desmonte no planificado por ciclo de avance). Las causas fundamentales de esta sobre-excavación sistemática se resumen en cuatro factores operacionales:"))
    c1.append(pb("<b>Mallas empíricas no adaptativas:</b> El diseño de distribución de barrenos se realizaba de manera estática y aproximada por el personal de perforación, sin recalibración físico-mecánica frente a los cambios litológicos y estructurales del frente."))
    c1.append(pb("<b>Sobrecarga energética en el corte:</b> Empleo de cargas altamente concentradas en el arranque sin cálculo preciso del alivio requerido para el taladro rimador de 102 mm, forzando la apertura de cuñas con excesivo confinamiento."))
    c1.append(pb("<b>Inexistencia de voladura controlada en contorno:</b> Carga de taladros de corona y hastiales con cartuchos de emulsión de 32 mm acoplados al barreno de 45 mm, transmitiendo presiones dinámicas superiores a 500 MPa directamente a la roca encajonante."))
    c1.append(pb("<b>Desviación angular en perforación:</b> Falta de guía láser y control de paralelismo en las plumas del jumbo, incrementando el burden en el fondo de los barrenos perimétricos hasta superar la distancia crítica de rotura."))
    c1.append(p("La auditoría de los reportes diarios de perforación de los jumbos Sandvik DD321 evidenció que los operadores tendían a sobre-perforar el frente ejecutando hasta 56 taladros por disparo, incorporando 'ayudas adicionales' en la corona sin sustento geomecánico. Esta práctica incrementaba la densidad de carga por unidad de superficie a más de 5.6 kg/m², pulverizando la roca en el contorno y destruyendo las trazas de las medias cañas."))
    c1.append(p("Asimismo, el análisis de desgaste de aceros reveló un consumo prematuro de brocas de botones de 45 mm (vida útil reducida a menos de 180 metros perforados frente al estándar de 250 m), debido a la desviación angular y al sobrecalentamiento por emboquillado en superficies irregulares dejadas por voladuras previas con alta sobre-excavación."))
    c1.append(pcap("[Poner imagen de: Nube de Puntos 3D de Escáner Láser mostrando la Sección Teórica vs. Cavidad Real Sobre-excavada]"))

    c1.append(ph2("1.4. Mecanismos Físicos y Geomecánicos de la Sobre-excavación"))
    c1.append(p("Desde la perspectiva de la mecánica de fragmentación de rocas por explosivos, la detonación de una carga confinada en un barreno genera un tren de ondas elásticas y plásticas de alta frecuencia que se propaga radialmente en el macizo rocoso a velocidades que superan los 4,500 m/s. La presión de detonación en el plano de Chapman-Jouguet genera inmediatamente una zona de trituración plástica hidrostática en el entorno milimétrico del barreno, seguida por la propagación de una onda compresional primaria (Onda P)."))
    c1.append(p("Cuando los barrenos perimétricos (corona y hastiales) son cargados con cartuchos de 32 mm acoplados sin desacoplamiento anular de aire, la presión efectiva aplicada sobre la pared del barreno ($P_{te}$) alcanza valores superiores a los 500 MPa. Dado que la resistencia a la compresión uniaxial de la roca intacta en Lincuna es $UCS = 180.05\text{ MPa}$, la relación de esfuerzos excede en casi tres veces la capacidad resistente del macizo, provocando la pulverización de la roca y la apertura incontrolada de fracturas radiales."))
    c1.append(p("Posteriormente, cuando la onda compresional $P$ alcanza la cara libre teórica de la galería, se refleja como una onda de tracción (Onda S / onda reflejada). Debido a que la resistencia a la tracción del macizo ($σ_t = 12.15\text{ MPa}$) es aproximadamente un quinceavo de su resistencia a la compresión ($σ_t \approx UCS / 15$), los esfuerzos de tracción inducidos superan holgadamente el límite de rotura frágil del macizo (<i>spalling</i> dinámico). Los gases de explosión a alta temperatura y presión (superior a 2,000 MPa) se infiltran a gran velocidad en estas discontinuidades abiertas, presurizando las paredes de las cuñas y desprendiendo bloques rocosos hacia el interior de la labor, destruyendo la línea de contorno de diseño y desarticulando el arco natural de autosoporte."))
    c1.append(p("La desarticulación del arco natural de sustentación de la galería genera un incremento en la zona de plastificación perimétrica, la cual se extiende hasta 1.50 metros dentro del macizo rocoso. En esta zona dañada, el módulo de elasticidad dinámico se reduce drásticamente, disminuyendo la capacidad de carga del macizo y forzando a que el sostenimiento artificial absorba la totalidad del peso de la columna de roca desprendida."))
    c1.append(pcap("[Poner imagen de: Esquema Teórico de Generación de Ondas P, Spalling por Tracción y Presurización de Grietas por Gases]"))

    c1.append(ph2("1.5. Modelo de Sobrecostos en el Ciclo Minero y Partida de Sostenimiento"))
    c1.append(p("La sobre-excavación no solo altera la geometría de la labor, sino que desestabiliza la estructura de costos operativos de la unidad minera. En la U.E.A. Lincuna, el estándar geomecánico para labores en roca Tipo III-B exige la aplicación de una capa de sostenimiento primario consistente en concreto proyectado (<i>shotcrete</i>) vía húmeda robotizado con fibra sintética estructural de 2 pulgadas de espesor nominal ($e = 0.05\text{ m}$)."))
    c1.append(p("El costo unitario auditado de producción, transporte y lanzado de shotcrete vía húmeda en Lincuna asciende a <b>$285.00 USD/m³</b> (incluyendo cemento Portland Tipo I, arena gruesa, gravilla 3/8\", aditivo acelerante ultra-rápido libre de álcalis, fibra sintética estructural macro, depreciación de robot lanzador Meyco / Robojet, compresor y mano de obra especializada)."))
    c1.append(p("Cuando se produce una sobrerotura del 34.36%, el perímetro de la excavación se incrementa y se generan cavidades irregulares y sobrebóvedas que deben ser rellenadas obligatoriamente para restablecer el perfil de autosoporte y evitar la formación de cuñas inestables. Para rellenar el exceso volumétrico de 22.75 m³ por disparo (considerando un factor de llenado técnico del 65%), se requiere un volumen real de shotcrete de <b>14.79 m³ por disparo</b>, generando un costo directo de sostenimiento de <b>$4,215.15 USD por disparo</b>."))
    c1.append(p("Adicionalmente, el carguío y transporte de las 61.42 TM de desmonte excedente por disparo genera sobrecostos en el ciclo minero:"))
    c1.append(pb("<b>Carguío mecanizado con Scooptramp (6 yd³):</b> $1.20 USD/TM $\times$ 61.42 TM = <b>$73.70 USD por disparo</b> (12 viajes adicionales de cuchara y 25 minutos de retraso en el ciclo)."))
    c1.append(pb("<b>Transporte subterráneo con Dumper (20 TM):</b> $1.80 USD/TM $\times$ 61.42 TM = <b>$110.55 USD por disparo</b> (3 viajes adicionales de volquete hasta echadero)."))
    c1.append(pb("<b>Sobrecosto total directo por disparo:</b> $4,215.15 + $73.70 + $110.55 = <b>$4,399.40 USD por disparo</b>."))
    c1.append(p("Para un programa anual de desarrollo minero de 2,000 metros lineales (equivalente a 575 disparos de avance), el impacto económico negativo acumulado de la sobre-excavación alcanzaba la alarmante cifra de <b>$2,529,655.00 USD anuales</b>, demostrando la imperiosa necesidad de una reingeniería matemática integral del proceso de perforación y voladura."))
    c1.append(pcap("[Poner imagen de: Gráfico de Cascada de Sobrecostos Unitarios y Pérdidas Anuales Consolidadas en Sostenimiento y Ciclo de Limpieza]"))

    c1.append(ph2("1.6. Árbol de Causas Raíz, Problema Central y Efectos Críticos"))
    c1.append(p("A fin de sistematizar las relaciones de causalidad del fenómeno investigado, se formuló el árbol de problemas del proyecto de tesis:"))
    c1.append(pb("<b>Causas Raíz:</b> (1) Ausencia de un sistema de diseño inteligente adaptativo al RMR; (2) Inexistencia de voladura controlada desacoplada en el contorno; (3) Inadecuada distribución geométrica de cargas en el área de tajeo; (4) Descalibración de factores de fijación en arrastres."))
    c1.append(pb("<b>Causas Directas:</b> Presiones de detonación en contorno superiores a 500 MPa; arranque empírico hiper-confinado; falta de paralelismo en barrenos perimétricos; ausencia de taladro de alivio escariado de gran diámetro."))
    c1.append(pb("<b>PROBLEMA CENTRAL:</b> Elevado índice de sobrerotura (34.36%) en frentes de avance horizontal de la U.E.A. Lincuna."))
    c1.append(pb("<b>Efectos Directos:</b> Sobre-excavación de 22.75 m³ de roca rota por disparo; consumo excesivo de shotcrete (14.79 m³/disparo); 61.42 TM adicionales de desmonte por ciclo; destrucción de medias cañas (HCF = 11.20%)."))
    c1.append(pb("<b>Efectos Finales:</b> Pérdida económica anual superior a $2.52 Millones de USD; retrasos en la preparación de reservas; desestabilización geomecánica de la corona y riesgo crítico de caída de rocas."))

    return c1
